from rag import search_rag


# ==========================================
# RAG SEARCH TOOL
# ==========================================

def rag_search(query):

    results = search_rag(
        query,
        top_k=3
    )

    if not results:
        return "No relevant information found."

    output = []

    for result in results:

        output.append(
            f"Page {result['page']}:\n"
            f"{result['text']}"
        )

    return "\n\n".join(output)


# ==========================================
# REPORT TOOL
# ==========================================

def create_report(title, content):

    filename = "kbtcoe_report.txt"

    report = f"""
========================================
{title}
========================================

{content}

========================================
Generated by AI Agent
========================================
"""

    with open(
        filename,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(report)

    # Return both the success message
    # and the actual report content.
    # This allows the next tool, such as
    # send_email, to use the report.

    return (
        f"Report created successfully: {filename}\n\n"
        f"{report}"
    )


# ==========================================
# TEST TOOLS
# ==========================================

if __name__ == "__main__":

    query = input(
        "\nEnter a question: "
    )

    result = rag_search(query)

    print(
        "\n========== RAG TOOL RESULT ==========\n"
    )

    print(result)